name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install pylint-exit
      run: |
        curl -o pylint-exit https://raw.githubusercontent.com/jongracecox/pylint-exit/master/pylint_exit.py
        chmod +x pylint-exit
        sudo ln -s $PWD/pylint-exit /usr/local/bin/pylint-exit
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=pylint/.pylintrc ./missforest/missforest.py || pylint-exit $?
      shell: bash
